# 服务端口
server:
  port: 9040

#日志配置
logging:
  level:
    root: info

#dubbo配置
dubbo:
  application:
    name: item-web
  protocol:
    name: dubbo
  #zk配置
  registry:
    address: 10.0.6.99:2181
    protocol: zookeeper
  scan:
    base-packages: com.zclorne.zmall
  #consumer 超时时间，开发阶段使用
  consumer:
    timeout: 6000
    #不检查服务存在，即允许先启动消费者
    check: false

#关闭缓存（即开启热部署）
spring:
  thymeleaf:
    cache: false