# 服务端口
server:
  port: 9010

#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zmail?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  notEmpty: true

#日志级别
logging:
  level: info

